
import os
import codecs

# Define contents
isl_content = """﻿; *** Inno Setup Chinese Simplified messages ***
[LangOptions]
LanguageName=Chinese Simplified
LanguageID=$0804
LanguageCodePage=65001

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=%1 卸载
InfoBeforeClickLabel=当您准备好继续时，请点击“下一步”。
InfoAfterClickLabel=当您准备好继续时，请点击“下一步”。
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)

SelectDirLabel3=安装程序将把 [name] 安装到下列文件夹中。
SelectDirBrowseLabel=点击“下一步”继续。如果您想选择其他文件夹，请点击“浏览”。
DiskSpaceMBLabel=至少需要有 [mb] MB 的可用磁盘空间。
ToContinueAndClickNext=点击“下一步”继续，或点击“取消”退出安装程序。
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=此程序将安装 [name/ver] 到您的计算机上。%n%n建议您在继续安装之前关闭所有其它应用程序。
WizardSelectDir=选择目标位置
SelectDirDesc=您想将 [name] 安装在哪里？
WizardSelectProgramGroup=选择开始菜单文件夹
SelectGroupDesc=您想在哪里放置程序的快捷方式？
SelectGroupLabel3=安装程序将把程序的快捷方式创建在下列开始菜单文件夹中。
SelectGroupBrowseLabel=点击“下一步”继续。如果您想选择其他文件夹，请点击“浏览”。
WizardReady=准备安装
ReadyLabel1=安装程序现在准备开始安装 [name] 到您的计算机上。
ReadyLabel2a=点击“安装”继续此安装程序。如果您想回顾或改变设置，请点击“上一步”。
InstallingLabel=正在安装 [name]，请稍候。
WizardInstalling=正在安装
WizardInfoBefore=安装前必读
InfoBeforeLabel=在继续安装之前，请阅读下列重要信息。
WizardInfoAfter=安装后必读
InfoAfterLabel=在继续安装之前，请阅读下列重要信息。
WizardFinished=安装向导完成
FinishedHeadingLabel=[name] 安装向导完成
FinishedLabelNoIcons=安装程序已在您的计算机中安装了 [name]。
FinishedLabel=安装程序已在您的计算机中安装了 [name]。此应用程序可以通过选择安装的快捷方式运行。
ClickFinish=点击“完成”退出安装程序。
ErrorCreatingDir=安装程序无法创建目录“%1”
ErrorTooManyFilesInDir=无法在目录“%1”中创建文件，因为里面包含太多文件
WizardSelectTasks=选择附加任务
SelectTasksDesc=您想要安装程序执行哪些附加任务？
SelectTasksLabel=选择您想要安装程序在安装 [name] 时执行的附加任务，然后点击“下一步”。

[CustomMessages]
CreateDesktopIcon=创建桌面快捷方式(&D)
AdditionalIcons=附加快捷方式:
LaunchProgram=启动 %1
"""

iss_content = """﻿; Script generated by Install-Agent Pro
#define MyAppName "设备故障统计"
#define MyAppVersion "1.0"
#define MyAppPublisher "QC-攻关小组"
#define MyAppExeName "DeviceDefectStats.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C6D9D8E0-9F1A-4B2C-8D3E-1F4A5B6C7D8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=no
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=Install
OutputBaseFilename=DeviceDefectStats_Setup_Fixed
SetupIconFile=app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "chinesesimplified"; MessagesFile: "ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "dist\DeviceDefectStats\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "app_icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\app_icon.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
"""

# Write files with UTF-8 BOM (utf-8-sig)
isl_content = isl_content.lstrip('\ufeff')
iss_content = iss_content.lstrip('\ufeff')

base_dir = r"E:\QC-攻关小组\正在进行项目\设备故障统计"
isl_path = os.path.join(base_dir, "ChineseSimplified.isl")
iss_path = os.path.join(base_dir, "setup_script.iss")

with open(isl_path, 'w', encoding='utf-8-sig') as f:
    f.write(isl_content)

with open(iss_path, 'w', encoding='utf-8-sig') as f:
    f.write(iss_content)

print("Files written successfully with UTF-8 BOM.")
